services:
  backend:
    build:
      # this need to be like this, to have access to both backend and database and not only "./backend"
      context: .
      dockerfile: backend/Dockerfile
    image: 2240596.azurecr.io/jokenpo-backend
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_SSL: "${DB_SSL}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${BACKEND_ADDR}:${BACKEND_PORT}/health"]
      interval: 20s
      timeout: 10s
      retries: 5

  statistics:
    build:
      # this need to be like this, to have access to both backend and database and not only "./backend"
      context: .
      dockerfile: statistics/Dockerfile
    image: 2240596.azurecr.io/jokenpo-statistics
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    env_file:
      - .env
    ports:
      - ${STATISTICS_PORT}:${STATISTICS_PORT}
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_SSL: "${DB_SSL}"
    depends_on:
      backend:
        condition: service_healthy
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      # args:
      #   VITE_BACKEND_URL: "${VITE_BACKEND_URL}"
      #   VITE_STATISTICS_URL: "${VITE_STATISTICS_URL}"
    image: 2240596.azurecr.io/jokenpo-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      VITE_BACKEND_URL: "${VITE_BACKEND_URL}"
      VITE_STATISTICS_URL: "${VITE_STATISTICS_URL}"
    depends_on:
      backend:
        condition: service_healthy
